defaults:
  title: JBoss Tools

textile:
  :no_span_caps: true

css_minifier: disabled
js_minifier: disabled
html_minifier: disabled


css_url: /stylesheets
fonts_url: /fonts
js_url: /javascripts

features_url: /documentation/features
images_url: /images/tools

minified: .min

profiles:
  development:
    minified:
    base_url: http://localhost:4242
    #theme_css_url: /theme/css/bootstrap/2.1.0.0.0
    #theme_js_url: /theme/js/libs/bootstrap/2.1.0.0.0
    #theme_fonts_url: /theme/fonts
    #theme_images_url: /theme/images
    theme_css_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/css/bootstrap/2.1.0.0.0
    theme_js_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/js/libs/bootstrap/2.1.0.0.0
    theme_fonts_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/fonts
    theme_images_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/images
    disqus: jbosstools-dev
  staging:
    base_url: http://preview-jbosstools.rhcloud.com/
    #theme_css_url: https://static-stg.jboss.org/theme/css/bootstrap/2.1.0.0.0
    #theme_js_url: https://static-stg.jboss.org/theme/js/libs/bootstrap/2.1.0.0.0
    #theme_fonts_url: https://static-stg.jboss.org/theme/fonts
    #theme_images_url: https://static-stg.jboss.org/theme/images
    theme_css_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/css/bootstrap/2.1.0.0.0
    theme_js_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/js/libs/bootstrap/2.1.0.0.0
    theme_fonts_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/fonts
    theme_images_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/images
    disqus: jbosstools-preview
  production:
    base_url: http://jboss.org/tools
    theme_css_url: https://static.jboss.org/theme/css/bootstrap/2.1.0.0.0
    theme_js_url: https://static.jboss.org/theme/js/libs/bootstrap/2.1.0.0.0
    theme_fonts_url: https://static.jboss.org/theme/fonts
    theme_images_url: https://static.jboss.org/theme/images

wget:
  enabled: false
  createGitIgnoreFiles: true
  options:
    - -q
    - -r
    - --no-host-directories
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
  urls:
    - http://static-stg.jboss.org/theme/css/bootstrap/2.1.0.0.0/bootstrap-community.css
    - http://static-stg.jboss.org/theme/js/libs/bootstrap/2.1.0.0.0/bootstrap-community.js
    - http://static-stg.jboss.org/theme/fonts/titilliumtext/
    - http://static-stg.jboss.org/theme/images/common/
    - http://static-stg.jboss.org/theme/images/community/
    - http://static-stg.jboss.org/theme/images/tools/
    
