defaults:
  title: JBoss Tools

textile:
  :no_span_caps: true

css_minifier: enabled
js_minifier: enabled
html_minifier: enabled


css_url: /stylesheets
fonts_url: /fonts
js_url: /javascripts

features_url: /documentation/features
images_url: /images/tools

minified: .min

theme_css_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/css/bootstrap/2.1.0.0.0
theme_js_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/js/libs/bootstrap/2.1.0.0.0
theme_fonts_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/fonts
theme_images_url: http://download.jboss.org/jbosstools/extras/temp-static/theme/images

profiles:
  development:
    base_url: http://localhost:4242
    css_minifier: disabled
    js_minifier: disabled
    html_minifier: disabled
    disqus: jbosstools-dev
  xcoulon:
    base_url: http://xcoulon.github.com/jbosstools-website
    disqus: jbosstools-preview
    deploy:
      host: github_pages
      repository: xcoulon
      branch: gh_pages
  
      
  


    
